AllCops:
  TargetRubyVersion: 2.4.1
  UseCache: true
  Exclude:
    - vendor/**/*
    - db/schema.rb

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AmbiguousBlockAssociation:
  Enabled: false
