development:
  adapter: postgresql
  encoding: unicode
  database: myeshop
  pool: 5
  #dpge
  #username: postgres
  #password: ""
  username: ice 
  password: "ice123"

production:
  adapter: postgresql
  encoding: unicode
  database: myeshop
  pool: 5
