development:
  adapter: postgresql
  encoding: unicode
  database: myeshop
  pool: 5
  username: postgres
  password: ""

production:
  adapter: postgresql
  encoding: unicode
  database: myeshop
  pool: 5
