test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: hltb_bot
  pool: 5
  username: postgres
  password: ""

production:
  adapter: postgresql
  encoding: unicode
  database: hltb_bot
  pool: 5
